from lda_model import lda_train_model


# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8.csv","main")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_0.csv","0")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_1.csv","1")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_2.csv","2")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_3.csv","3")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_4.csv","4")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_5.csv","5")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_6.csv","6")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_7.csv","7")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_8.csv","8")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_9.csv","9")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_10.csv","10")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_11.csv","11")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_12.csv","12")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_13.csv","13")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_14.csv","14")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_15.csv","15")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_16.csv","16")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_17.csv","17")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_18.csv","18")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_19.csv","19")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_20.csv","20")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_21.csv","21")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_22.csv","22")
lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 8_23.csv","23")

# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7.csv","main")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_0.csv","0")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_1.csv","1")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_2.csv","2")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_3.csv","3")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_4.csv","4")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_5.csv","5")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_6.csv","6")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_7.csv","7")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_8.csv","8")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_9.csv","9")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_10.csv","10")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_11.csv","11")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_12.csv","12")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_13.csv","13")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_14.csv","14")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_15.csv","15")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_16.csv","16")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_17.csv","17")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_18.csv","18")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_19.csv","19")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_20.csv","20")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_21.csv","21")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_22.csv","22")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 7_23.csv","23")

# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6.csv","main")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_0.csv","0")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_1.csv","1")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_2.csv","2")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_3.csv","3")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_4.csv","4")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_5.csv","5")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_6.csv","6")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_7.csv","7")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_8.csv","8")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_9.csv","9")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_10.csv","10")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_11.csv","11")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_12.csv","12")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_13.csv","13")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_14.csv","14")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_15.csv","15")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_16.csv","16")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_17.csv","17")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_18.csv","18")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_19.csv","19")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_20.csv","20")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_21.csv","21")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_22.csv","22")
# lda_train_model("./lda/[pp_FULL] dataset_yolanda nov 6_23.csv","23")




